/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputTag: typeof import('@arco-design/web-vue')['InputTag']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpance: typeof import('@arco-design/web-vue')['Spance']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    Chatroom: typeof import('./components/Chatroom/index.vue')['default']
    Config: typeof import('./components/Config/index.vue')['default']
    Contacts: typeof import('./components/Contacts/index.vue')['default']
    ContactsAttirbutes: typeof import('./components/Contacts/contactsAttirbutes.vue')['default']
    ContactsRelations: typeof import('./components/Contacts/contactsRelations.vue')['default']
    Conversation: typeof import('./components/Conversation/index.vue')['default']
    Group: typeof import('./components/Group/index.vue')['default']
    HistoryMessage: typeof import('./components/Message/historyMessage.vue')['default']
    Login: typeof import('./components/Login/index.vue')['default']
    ManageChatroom: typeof import('./components/Chatroom/manageChatroom.vue')['default']
    ManageChatroomAttribute: typeof import('./components/Chatroom/manageChatroomAttribute.vue')['default']
    ManageGroup: typeof import('./components/Group/manageGroup.vue')['default']
    ManageGroupAttribute: typeof import('./components/Group/manageGroupAttribute.vue')['default']
    ManageGroupMember: typeof import('./components/Group/manageGroupMember.vue')['default']
    MangeChatroomMember: typeof import('./components/Chatroom/mangeChatroomMember.vue')['default']
    Message: typeof import('./components/Message/index.vue')['default']
    OnlineStatusSub: typeof import('./components/Contacts/onlineStatusSub.vue')['default']
    PinMessage: typeof import('./components/Message/pinMessage.vue')['default']
    ReactionMessage: typeof import('./components/Message/reactionMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
